address review comments
Signed-off-by: Aylei <rayingecho@gmail.com>

diff --git a/.github/workflows/pypi-nightly-build.yml b/.github/workflows/pypi-nightly-build.yml
--- a/.github/workflows/pypi-nightly-build.yml
+++ b/.github/workflows/pypi-nightly-build.yml
@@ -5,7 +5,7 @@ on:
   workflow_dispatch:
     inputs:
       build_number:
-        description: 'Additional build number for same-day releases, counts from 1 (0 is reserved for the first release of the day, which omits the build number in the version string).'
+        description: 'Additional build number for same-day releases, from 1 to 99 (0 is reserved for the first release of the day).'
         required: false
         type: number
         default: 0
@@ -46,10 +46,12 @@ jobs:
           --user
       - name: Set release version
         run: |
-          RELEASE_VERSION=$(date +%Y%m%d)
-          if [ "${{ inputs.build_number }}" -gt 0 ]; then
-            RELEASE_VERSION="${RELEASE_VERSION}0${{ inputs.build_number }}"
+          if [ "${{ inputs.build_number }}" -lt 0 ] || [ "${{ inputs.build_number }}" -gt 99 ]; then
+            echo "Error: build_number must be a number between 0 and 99"
+            exit 1
           fi
+          # Format the version as YYYYMMDD00, YYYYMMDD01...
+          RELEASE_VERSION="$(date +%Y%m%d)$(printf "%02d" "${{ inputs.build_number }}")"
           sed -i "s/{{SKYPILOT_COMMIT_SHA}}/${{ github.sha }}/g" sky/__init__.py
           sed -i "s/__version__ = '.*'/__version__ = '1.0.0.dev${RELEASE_VERSION}'/g" sky/__init__.py
           sed -i "s/name='skypilot',/name='skypilot-nightly',/g" sky/setup_files/setup.py
